interface DocumentMetaProps {
  title: string;
  generatedBy: string;
  generatedDate: string;
  generatedTime: string;
  academicSession?: string;
  moduleName: string;
  totalRecords: number;
  documentId?: string;
}

export function DocumentMeta({
  title,
  generatedBy,
  generatedDate,
  generatedTime,
  academicSession,
  moduleName,
  totalRecords,
  documentId,
}: DocumentMetaProps) {
  return (
    <div className="bg-gray-50 border rounded-lg p-3 mb-4 text-xs">
      <div className="grid grid-cols-2 gap-x-6 gap-y-1">
        <div className="flex justify-between">
          <span className="text-gray-500">Document:</span>
          <span className="font-medium">{documentId || `${moduleName.replace(/\s+/g, "_")}_${generatedDate.replace(/[\s-]/g, "")}`}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">Module:</span>
          <span className="font-medium">{moduleName}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">Generated By:</span>
          <span className="font-medium">{generatedBy}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">Total Records:</span>
          <span className="font-medium">{totalRecords}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">Date:</span>
          <span className="font-medium">{generatedDate}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">Time:</span>
          <span className="font-medium">{generatedTime}</span>
        </div>
        {academicSession && (
          <div className="flex justify-between">
            <span className="text-gray-500">Academic Session:</span>
            <span className="font-medium">{academicSession}</span>
          </div>
        )}
      </div>
    </div>
  );
}
