# Generated by Django 6.0.4 on 2026-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="mobile"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
