# Generated by Django 6.0.6 on 2026-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_otp_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
