# Generated by Django 6.0.4 on 2026-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_otp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
