# Generated by Django 6.0.4 on 2026-07-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_customuser_needs_activation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
