# Generated by Django 6.0.4 on 2026-07-24 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=255)),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML content with {{ variable }} placeholders"
                    ),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain text fallback"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(default="EduSphere", max_length=255),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="institution/"),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("principal_name", models.CharField(blank=True, max_length=255)),
                (
                    "principal_signature",
                    models.ImageField(blank=True, null=True, upload_to="institution/"),
                ),
                (
                    "email_footer",
                    models.TextField(
                        blank=True, help_text="Additional footer text for emails"
                    ),
                ),
                (
                    "brand_color_primary",
                    models.CharField(default="#2563eb", max_length=7),
                ),
                (
                    "brand_color_secondary",
                    models.CharField(default="#1e40af", max_length=7),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution Setting",
                "verbose_name_plural": "Institution Settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("assignment_created", "Assignment Created"),
                            ("assignment_updated", "Assignment Updated"),
                            ("assignment_deadline", "Assignment Deadline"),
                            ("results_published", "Results Published"),
                            ("rechecked_result", "Rechecked Result Published"),
                            ("fee_generated", "Fee Generated"),
                            ("fee_reminder", "Fee Reminder"),
                            ("admission_approved", "Admission Approved"),
                            ("admission_rejected", "Admission Rejected"),
                            ("subject_approved", "Subject Request Approved"),
                            ("subject_rejected", "Subject Request Rejected"),
                            ("student_promoted", "Student Promoted"),
                            ("otp_verification", "OTP Verification"),
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("maintenance", "Maintenance"),
                            ("assignment_announcement", "Assignment Announcement"),
                            ("subject_announcement", "Subject Announcement"),
                            ("class_announcement", "Class Announcement"),
                            ("school_announcement", "School Announcement"),
                            ("holiday_notice", "Holiday Notice"),
                            ("circular", "Circular"),
                            ("event", "Event"),
                            ("emergency", "Emergency Notice"),
                            ("exam_announcement", "Exam Announcement"),
                            ("welcome", "Welcome Email"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reminder_interval_hours", models.IntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_students", "All Students"),
                            ("all_teachers", "All Teachers"),
                            ("all_staff", "All Staff"),
                            ("specific_students", "Specific Students"),
                            ("specific_teachers", "Specific Teachers"),
                            ("specific_class", "Specific Class"),
                            ("specific_section", "Specific Section"),
                            ("specific_subject", "Specific Subject"),
                            ("entire_school", "Entire School"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["notification_type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("assignment_created", "Assignment Created"),
                            ("assignment_updated", "Assignment Updated"),
                            ("assignment_deadline", "Assignment Deadline"),
                            ("results_published", "Results Published"),
                            ("rechecked_result", "Rechecked Result Published"),
                            ("fee_generated", "Fee Generated"),
                            ("fee_reminder", "Fee Reminder"),
                            ("admission_approved", "Admission Approved"),
                            ("admission_rejected", "Admission Rejected"),
                            ("subject_approved", "Subject Request Approved"),
                            ("subject_rejected", "Subject Request Rejected"),
                            ("student_promoted", "Student Promoted"),
                            ("otp_verification", "OTP Verification"),
                            ("password_reset", "Password Reset"),
                            ("email_verification", "Email Verification"),
                            ("maintenance", "Maintenance"),
                            ("assignment_announcement", "Assignment Announcement"),
                            ("subject_announcement", "Subject Announcement"),
                            ("class_announcement", "Class Announcement"),
                            ("school_announcement", "School Announcement"),
                            ("holiday_notice", "Holiday Notice"),
                            ("circular", "Circular"),
                            ("event", "Event"),
                            ("emergency", "Emergency Notice"),
                            ("exam_announcement", "Exam Announcement"),
                            ("welcome", "Welcome Email"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_students", "All Students"),
                            ("all_teachers", "All Teachers"),
                            ("all_staff", "All Staff"),
                            ("specific_students", "Specific Students"),
                            ("specific_teachers", "Specific Teachers"),
                            ("specific_class", "Specific Class"),
                            ("specific_section", "Specific Section"),
                            ("specific_subject", "Specific Subject"),
                            ("entire_school", "Entire School"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_class", models.CharField(blank=True, max_length=50)),
                ("target_section", models.CharField(blank=True, max_length=50)),
                ("target_subject", models.CharField(blank=True, max_length=100)),
                ("target_user_ids", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("activation_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Notification Created"),
                            ("priority_changed", "Priority Changed"),
                            ("priority_overridden", "Priority Overridden"),
                            ("read", "Read"),
                            ("deleted", "Deleted"),
                            ("expired", "Expired"),
                            ("email_sent", "Email Sent"),
                            ("email_failed", "Email Failed"),
                            ("retry", "Retry"),
                            ("admin_override", "Admin Override"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="notification.notification",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Audit Log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_status",
                    models.CharField(
                        choices=[("unread", "Unread"), ("read", "Read")],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notification.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("websocket", "WebSocket"),
                            ("system", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="notification.notification",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="notification.notificationrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "status"],
                name="notificatio_notific_f04cee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "created_at"], name="notificatio_priorit_d43c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["expires_at"], name="notificatio_expires_e87528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["user", "read_status"], name="notificatio_user_id_7fbc10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["delivery_status"], name="notificatio_deliver_46904e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationrecipient",
            unique_together={("notification", "user")},
        ),
    ]
