# Generated by Django 6.0.4 on 2026-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionsettings",
            name="director_message",
            field=models.TextField(
                blank=True, help_text="Director's message for public display"
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="public_address",
            field=models.TextField(blank=True, help_text="Public institution address"),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="public_email",
            field=models.EmailField(
                blank=True, help_text="Public contact email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="public_phone",
            field=models.CharField(
                blank=True, help_text="Public contact phone", max_length=50
            ),
        ),
    ]
