# Generated by Django 6.0.4 on 2026-07-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_institutionsettings_director_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionsettings",
            name="public_website_data_mode",
            field=models.CharField(
                choices=[("DEMO", "Demo Data"), ("LIVE", "Live Data")],
                default="LIVE",
                help_text="Director-controlled public website data mode",
                max_length=10,
            ),
        ),
    ]
