# Generated by Django 6.0.6 on 2026-06-15 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0002_studentprofile_blood_group_studentprofile_gender_and_more"),
        ("teacher", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("video_title", models.CharField(blank=True, max_length=200)),
                (
                    "featured_students",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, achievement, class} objects",
                    ),
                ),
                (
                    "top_students",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {rank, name, class, percentage} objects",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=100)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("father_name", models.CharField(blank=True, max_length=100)),
                ("mother_name", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("previous_board", models.CharField(blank=True, max_length=100)),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Science, Commerce, Arts",
                        max_length=50,
                    ),
                ),
                (
                    "entrance_test_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "entrance_test_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "marks_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {subject, pass, obtained, total}",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission Application",
                "verbose_name_plural": "Admission Applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_info",
                    models.TextField(
                        blank=True, help_text="Banner text displayed on admission page"
                    ),
                ),
                (
                    "application_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("intake_capacity", models.IntegerField(default=0)),
                (
                    "important_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {event, date} objects",
                    ),
                ),
                (
                    "notices",
                    models.JSONField(
                        blank=True, default=list, help_text="List of notice strings"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admission Page Content",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("label", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="HomepageFeaturedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage/")),
                ("label", models.CharField(blank=True, max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("starred", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SubjectRequestControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subject Request Control",
                "verbose_name_plural": "Subject Request Controls",
            },
        ),
        migrations.CreateModel(
            name="AdmissionVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("info_requested", "Info Requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="administration.admissionapplication",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Verification",
                "verbose_name_plural": "Admission Verifications",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("student", "Student Document"),
                            ("teacher", "Teacher Document"),
                            ("admission", "Admission Document"),
                            ("answer_script", "Answer Script"),
                            ("resource", "Resource File"),
                            ("gallery", "Gallery Image"),
                            ("profile", "Profile Image"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "related_model",
                    models.CharField(
                        blank=True,
                        help_text="e.g. student, teacher, admission",
                        max_length=100,
                    ),
                ),
                ("related_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Storage",
                "verbose_name_plural": "Document Storage",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("sports", "Sports"),
                            ("cultural", "Cultural"),
                            ("meeting", "Meeting"),
                            ("ceremony", "Ceremony"),
                            ("workshop", "Workshop"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_banners/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=50)),
                (
                    "classes",
                    models.JSONField(
                        blank=True, default=list, help_text="List of class names"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("academic_year", models.CharField(default="2026-27", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="student.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AnswerScriptUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_file", models.FileField(upload_to="admin_answer_scripts/")),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Evaluation"),
                            ("evaluating", "Evaluating"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_answer_scripts",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_answer_scripts",
                        to="student.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_evaluation_queue",
                        to="teacher.teacherprofile",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_scripts",
                        to="administration.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=100)),
                ("class_name", models.CharField(blank=True, max_length=20)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="administration.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="e.g. student, teacher, attendance", max_length=100
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("pdf", "PDF")],
                        max_length=20,
                    ),
                ),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Log",
                "verbose_name_plural": "Export Logs",
                "ordering": ["-exported_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("all_students", "All Students"),
                            ("all_teachers", "All Teachers"),
                            ("specific_students", "Specific Students"),
                            ("specific_teachers", "Specific Teachers"),
                            ("class", "Specific Class"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_class",
                    models.CharField(
                        blank=True,
                        help_text="Only for 'class' recipient type",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of user IDs for specific recipients",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Broadcast",
                "verbose_name_plural": "Notification Broadcasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentRegistrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_logs",
                        to="administration.admissionapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_student_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_logs",
                        to="student.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Registration Log",
                "verbose_name_plural": "Student Registration Logs",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassTeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(help_text="e.g. X, XI", max_length=20)),
                ("academic_year", models.CharField(default="2026-27", max_length=20)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teacher_assignments",
                        to="teacher.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Teacher Assignment",
                "verbose_name_plural": "Class Teacher Assignments",
                "unique_together": {("teacher", "class_name", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="EvaluationTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_scripts", models.IntegerField(default=0)),
                ("pending", models.IntegerField(default=0)),
                ("evaluating", models.IntegerField(default=0)),
                ("completed", models.IntegerField(default=0)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_tracking",
                        to="student.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_tracking",
                        to="teacher.teacherprofile",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_tracking",
                        to="administration.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Tracking",
                "unique_together": {("teacher", "exam", "subject")},
            },
        ),
        migrations.CreateModel(
            name="FacultyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("half_day", "Half Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_faculty_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_attendance",
                        to="teacher.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Attendance",
                "verbose_name_plural": "Faculty Attendances",
                "unique_together": {("teacher", "date")},
            },
        ),
        migrations.CreateModel(
            name="PublishedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(blank=True, max_length=5)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_results",
                        to="administration.exam",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_published_results",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_published_results",
                        to="student.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "unique_together": {("exam", "student", "subject")},
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_classes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of class names e.g. ['X-A', 'X-B']",
                    ),
                ),
                ("academic_year", models.CharField(default="2026-27", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_allocations",
                        to="student.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_allocations",
                        to="teacher.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Subject Allocation",
                "verbose_name_plural": "Teacher Subject Allocations",
                "unique_together": {("teacher", "subject", "academic_year")},
            },
        ),
    ]
