# Generated by Django 6.0.4 on 2026-07-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="e.g. 2026-27", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AlterField(
            model_name="exportlog",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("csv", "CSV"),
                    ("excel", "Excel"),
                    ("pdf", "PDF"),
                    ("zip", "ZIP"),
                    ("print", "Print"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="e.g. X-A", max_length=20)),
                ("section", models.CharField(blank=True, max_length=10)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="administration.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "classes",
                "unique_together": {("name", "academic_session")},
            },
        ),
    ]
