# Generated by Django 6.0.4 on 2026-07-23 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_auditlog"),
        ("student", "0005_studentsubject_academic_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                (
                    "academic_session",
                    models.CharField(default="2026-27", max_length=20),
                ),
                (
                    "late_fine_per_day",
                    models.DecimalField(decimal_places=2, default=50, max_digits=10),
                ),
                ("gst_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["class_name"],
                "unique_together": {("class_name", "academic_session")},
            },
        ),
        migrations.CreateModel(
            name="FeeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                            ("one-time", "One-Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="administration.feestructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinanceActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("structure_created", "Structure Created"),
                            ("structure_updated", "Structure Updated"),
                            ("structure_deleted", "Structure Deleted"),
                            ("payment_verified", "Payment Verified"),
                            ("payment_rejected", "Payment Rejected"),
                            ("refund_initiated", "Refund Initiated"),
                            ("refund_completed", "Refund Completed"),
                            ("scholarship_granted", "Scholarship Granted"),
                            ("scholarship_revoked", "Scholarship Revoked"),
                            ("offline_payment", "Offline Payment Recorded"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scholarships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="student.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                (
                    "academic_session",
                    models.CharField(default="2026-27", max_length=20),
                ),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fine",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "scholarship_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_paid", "Not Paid"),
                            ("pending_verification", "Pending Verification"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_paid",
                        max_length=25,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "transaction_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "advance_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("initiated", "Initiated"),
                            ("completed", "Completed"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("refund_initiated_at", models.DateTimeField(blank=True, null=True)),
                ("refund_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("student", "month", "academic_session")},
            },
        ),
    ]
