# Generated by Django 6.0.4 on 2026-07-23 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0004_feestructure_feecomponent_financeactivitylog_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Letterhead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("branding", models.JSONField(blank=True, default=dict)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="letterheads/logos/"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="letterheads/banners/"
                    ),
                ),
                ("header_spacing", models.IntegerField(default=40)),
                ("footer_spacing", models.IntegerField(default=40)),
                ("left_margin", models.IntegerField(default=20)),
                ("right_margin", models.IntegerField(default=20)),
                ("primary_color", models.CharField(default="#1e40af", max_length=20)),
                ("secondary_color", models.CharField(default="#64748b", max_length=20)),
                ("footer_text", models.TextField(blank=True)),
                ("watermark_text", models.CharField(blank=True, max_length=100)),
                ("signature_placeholder", models.TextField(blank=True)),
                ("school_seal_placeholder", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_letterheads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
