# Generated by Django 6.0.4 on 2026-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_letterhead"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectrequestcontrol",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subjectrequestcontrol",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
