# Generated by Django 6.0.4 on 2026-07-23 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0006_subjectrequestcontrol_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answerscriptupload",
            name="batch_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="draft_marks",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="draft_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="registration_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="roll_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="script_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="section",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending_upload", "Pending Upload"),
                    ("uploaded", "Uploaded"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("assigned", "Assigned to Teacher"),
                    ("evaluation_completed", "Evaluation Completed"),
                    ("archived", "Archived"),
                ],
                default="pending_upload",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answerscriptupload",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="answerscriptupload",
            name="script_file",
            field=models.FileField(
                blank=True, null=True, upload_to="staff_answer_scripts/"
            ),
        ),
        migrations.AlterField(
            model_name="answerscriptupload",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
            },
        ),
    ]
