# Generated by Django 6.0.4 on 2026-07-23 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0007_answerscriptupload_batch_id_and_more"),
        ("student", "0005_studentsubject_academic_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptBatchProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(db_index=True, max_length=50)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verifying", "Verifying"),
                            ("passed", "All Passed"),
                            ("failed", "One or More Failed"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_scripts", models.IntegerField(default=0)),
                ("passed_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("flagged_count", models.IntegerField(default=0)),
                ("processing_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_processing",
                        to="administration.exam",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_processing",
                        to="student.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Script Batch Processing",
                "verbose_name_plural": "Script Batch Processing",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScriptProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending OCR"),
                            ("processing", "Processing OCR"),
                            ("completed", "OCR Completed"),
                            ("failed", "OCR Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ocr_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("ocr_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ocr_error_message", models.TextField(blank=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("extracting", "Extracting Metadata"),
                            ("indexing", "Indexing Pages"),
                            ("matching", "Matching Student"),
                            ("validating", "Validating"),
                            ("completed", "Processing Completed"),
                            ("failed", "Processing Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("passed", "Verification Passed"),
                            ("failed", "Verification Failed"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("extracted_metadata", models.JSONField(blank=True, default=dict)),
                ("total_pages", models.IntegerField(blank=True, null=True)),
                ("expected_pages", models.IntegerField(blank=True, null=True)),
                ("missing_pages", models.JSONField(blank=True, default=list)),
                ("duplicate_pages", models.JSONField(blank=True, default=list)),
                (
                    "match_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("unmatched", "Unmatched"),
                            ("ambiguous", "Ambiguous"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("detected_roll_number", models.CharField(blank=True, max_length=20)),
                ("roll_verified", models.BooleanField(default=False)),
                ("roll_mismatch_reason", models.TextField(blank=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "duplicate_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scripts",
                        to="administration.scriptbatchprocessing",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="administration.scriptprocessing",
                    ),
                ),
                (
                    "matched_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="script_processing_matches",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "script",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing",
                        to="administration.answerscriptupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Script Processing",
                "verbose_name_plural": "Script Processing",
                "ordering": ["-created_at"],
            },
        ),
    ]
