# Generated by Django 6.0.4 on 2026-07-24 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0009_gradeboundary_resultpublication_studentresult"),
        ("student", "0005_studentsubject_academic_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("from_class", models.CharField(max_length=20)),
                (
                    "min_percentage",
                    models.DecimalField(decimal_places=2, default=40, max_digits=5),
                ),
                (
                    "min_attendance_percentage",
                    models.DecimalField(decimal_places=2, default=75, max_digits=5),
                ),
                ("max_failed_subjects", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promotion Rule",
                "verbose_name_plural": "Promotion Rules",
                "ordering": ["from_class"],
            },
        ),
        migrations.AddField(
            model_name="academicsession",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Archived sessions are read-only"
            ),
        ),
        migrations.CreateModel(
            name="AcademicSessionRollover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "copy_options",
                    models.JSONField(default=list, help_text="List of items to copy"),
                ),
                ("copy_results", models.JSONField(blank=True, default=dict)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollovers_from",
                        to="administration.academicsession",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_rollovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollback_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollovers_rolled_back",
                        to="administration.academicsessionrollover",
                    ),
                ),
                (
                    "to_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollovers_to",
                        to="administration.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Session Rollover",
                "verbose_name_plural": "Academic Session Rollovers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_class", models.CharField(max_length=20)),
                ("from_section", models.CharField(blank=True, max_length=10)),
                ("to_class", models.CharField(max_length=20)),
                ("to_section", models.CharField(blank=True, max_length=10)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("promote", "Promoted"),
                            ("repeat", "Repeated"),
                            ("detain", "Detained"),
                            ("bulk_promote", "Bulk Promoted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_session_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_logs_from",
                        to="administration.academicsession",
                    ),
                ),
                (
                    "academic_session_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_logs_to",
                        to="administration.academicsession",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollback_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to original log if this is a rollback entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollbacks",
                        to="administration.promotionlog",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_logs",
                        to="student.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Log",
                "verbose_name_plural": "Promotion Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPromotionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                ("section", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("promoted", "Promoted"),
                            ("repeated", "Repeated"),
                            ("detained", "Detained"),
                            ("completed", "Completed"),
                            ("left", "Left School"),
                        ],
                        default="promoted",
                        max_length=20,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_histories",
                        to="administration.academicsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_history",
                        to="student.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Promotion History",
                "verbose_name_plural": "Student Promotion Histories",
                "ordering": ["-academic_session__start_date"],
                "unique_together": {("student", "academic_session")},
            },
        ),
    ]
