# Generated by Django 6.0.4 on 2026-07-25 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0010_promotionrule_academicsession_is_archived_and_more"),
        ("student", "0005_studentsubject_academic_session"),
        ("teacher", "0004_chapter_topic_classchapterprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlindRecheckingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved – Awaiting Re-evaluation"),
                            ("re_evaluating", "Re-evaluation In Progress"),
                            ("comparing", "Comparing Results"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed – Window Expired"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                (
                    "marks_obtained_original",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_marks_original",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade_original", models.CharField(blank=True, max_length=5)),
                (
                    "second_evaluator_script_id",
                    models.CharField(
                        blank=True,
                        help_text="Anonymous script ID for blind evaluation (e.g. RECHK-XXXXX)",
                        max_length=20,
                    ),
                ),
                (
                    "second_evaluator_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "second_evaluator_total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("second_evaluator_remarks", models.TextField(blank=True)),
                (
                    "second_evaluator_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("evaluating", "Evaluating"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "second_evaluator_assigned_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "second_evaluator_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "marks_difference",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "rechecking_policy_applied",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("use_higher", "Use Higher Marks"),
                            ("use_average", "Use Average Marks"),
                            ("use_new", "Use New Marks"),
                            ("use_policy", "Use Institution Policy"),
                        ],
                        default="use_policy",
                        max_length=20,
                    ),
                ),
                ("is_revised", models.BooleanField(default=False)),
                (
                    "marks_obtained_revised",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_marks_revised",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade_revised", models.CharField(blank=True, max_length=5)),
                (
                    "rechecking_window_deadline",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("window_expired_notified", models.BooleanField(default=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecking_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rechecking_requests",
                        to="administration.exam",
                    ),
                ),
                (
                    "original_evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_rechecking_scripts",
                        to="teacher.teacherprofile",
                    ),
                ),
                (
                    "original_published_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecking_original",
                        to="administration.publishedresult",
                    ),
                ),
                (
                    "original_script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecking_requests",
                        to="administration.answerscriptupload",
                    ),
                ),
                (
                    "revised_published_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecking_revisions",
                        to="administration.publishedresult",
                    ),
                ),
                (
                    "second_evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecking_evaluations",
                        to="teacher.teacherprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rechecking_requests",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "student_result_unlocked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecking_unlocks",
                        to="administration.studentresult",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rechecking_requests",
                        to="student.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechecking Request",
                "verbose_name_plural": "Rechecking Requests",
                "ordering": ["-requested_at"],
                "unique_together": {("student", "exam", "subject", "status")},
            },
        ),
    ]
