# Generated by Django 6.0.4 on 2026-07-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0011_blindrecheckingrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeepayment",
            name="clearance_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="correction_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="correction_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="correction_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="correction_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("correction_requested", "Correction Requested"),
                    ("correction_approved", "Correction Approved"),
                    ("refund_requested", "Refund Requested"),
                    ("refund_approved", "Refund Approved"),
                ],
                default="none",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="fee_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="administration.feecomponent",
            ),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="paid_at_fine",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fine amount at time of payment — frozen for history",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="administration.studentfeepayment",
            ),
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="financeactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("structure_created", "Structure Created"),
                    ("structure_updated", "Structure Updated"),
                    ("structure_deleted", "Structure Deleted"),
                    ("fees_generated", "Fees Generated"),
                    ("payment_recorded", "Payment Recorded"),
                    ("payment_verified", "Payment Verified"),
                    ("payment_rejected", "Payment Rejected"),
                    ("refund_initiated", "Refund Initiated"),
                    ("refund_completed", "Refund Completed"),
                    ("correction_requested", "Correction Requested"),
                    ("correction_approved", "Correction Approved"),
                    ("scholarship_granted", "Scholarship Granted"),
                    ("scholarship_revoked", "Scholarship Revoked"),
                    ("offline_payment", "Offline Payment Recorded"),
                    ("overdue_notification", "Overdue Notification Sent"),
                    ("clearance_deadline_set", "Clearance Deadline Set"),
                    ("admission_fee_recorded", "Admission Fee Recorded"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="studentfeepayment",
            name="month",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="studentfeepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_due", "Not Due"),
                    ("not_paid", "Not Paid"),
                    ("overdue", "Overdue"),
                    ("pending_verification", "Pending Verification"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="not_paid",
                max_length=25,
            ),
        ),
    ]
