# Generated by Django 6.0.4 on 2026-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0012_fee_v1_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
