# Generated by Django 6.0.4 on 2026-07-26 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0013_teachersubjectallocation_is_primary"),
        ("student", "0005_studentsubject_academic_session"),
        ("teacher", "0006_timetableentry_unique_teacher_time_slot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSubjectConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(help_text="e.g. X-A", max_length=20)),
                (
                    "max_additional_subjects",
                    models.IntegerField(
                        default=2, help_text="Maximum additional subjects per student"
                    ),
                ),
                (
                    "max_specialized",
                    models.IntegerField(
                        default=2, help_text="Maximum specialized subjects"
                    ),
                ),
                (
                    "max_enriched",
                    models.IntegerField(
                        default=2, help_text="Maximum enriched subjects"
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Subject Configuration",
            },
        ),
        migrations.AlterUniqueTogether(
            name="classteacherassignment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teachersubjectallocation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="academicsession",
            name="subject_request_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for subject requests", null=True
            ),
        ),
        migrations.AddField(
            model_name="academicsession",
            name="subject_request_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable/disable subject requests for this session",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="capacity",
            field=models.IntegerField(default=0, help_text="Maximum student capacity"),
        ),
        migrations.AddField(
            model_name="class",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subjectrequestcontrol",
            name="max_additional_subjects",
            field=models.IntegerField(
                default=2, help_text="Maximum additional subjects per student"
            ),
        ),
        migrations.AddField(
            model_name="subjectrequestcontrol",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_request_controls",
                to="administration.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="academic_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_allocations",
                to="administration.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="deallocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deallocated_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="deallocation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="deallocation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="draft",
            field=models.BooleanField(
                default=False,
                help_text="Draft allocation from rollover awaiting admin confirmation",
            ),
        ),
        migrations.AddField(
            model_name="teachersubjectallocation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="subjectrequestcontrol",
            unique_together={("session",)},
        ),
        migrations.AlterUniqueTogether(
            name="teachersubjectallocation",
            unique_together={("teacher", "subject", "academic_session")},
        ),
        migrations.AddConstraint(
            model_name="classteacherassignment",
            constraint=models.UniqueConstraint(
                fields=("class_name", "academic_year"),
                name="unique_class_teacher_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="classteacherassignment",
            constraint=models.UniqueConstraint(
                fields=("teacher", "class_name", "academic_year"),
                name="unique_teacher_class_year",
            ),
        ),
        migrations.AddField(
            model_name="classsubjectconfig",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subject_configs",
                to="administration.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="classsubjectconfig",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Available subjects for this class",
                related_name="class_configs",
                to="student.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubjectconfig",
            unique_together={("class_name", "academic_session")},
        ),
    ]
