# Generated by Django 6.0.4 on 2026-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0015_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("export", "Export"),
                    ("upload", "Upload"),
                    ("download", "Download"),
                    ("rate_limit_exceeded", "Rate Limit Exceeded"),
                    ("access_denied", "Access Denied"),
                    ("fee_correction", "Fee Correction"),
                    ("fee_refund", "Fee Refund"),
                    ("promotion", "Promotion"),
                    ("rollback", "Rollback"),
                    ("result_publish", "Result Published"),
                    ("rechecking", "Rechecking"),
                    ("role_change", "Role Change"),
                    ("deactivation", "Deactivation"),
                    ("github_linked", "GitHub Account Linked"),
                    ("github_unlinked", "GitHub Account Unlinked"),
                    (
                        "github_login_failed_unbound",
                        "GitHub Login Failed - Unbound Account",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
