# Generated by Django 6.0.4 on 2026-07-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0016_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("report_card", "Report Card"),
                            ("marksheet", "Marksheet"),
                            ("transcript", "Transcript"),
                            ("fee_receipt", "Fee Receipt"),
                            ("student_report", "Student Performance Report"),
                            ("attendance_report", "Attendance Report"),
                            ("transfer_certificate", "Transfer Certificate"),
                            ("bonafide", "Bonafide Certificate"),
                            ("conduct_certificate", "Conduct Certificate"),
                            ("custom", "Custom Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        help_text="DOCX template file with {{ placeholders }}",
                        upload_to="templates/",
                    ),
                ),
                ("placeholder_registry", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "ordering": ["document_type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_version", models.PositiveIntegerField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("report_card", "Report Card"),
                            ("marksheet", "Marksheet"),
                            ("transcript", "Transcript"),
                            ("fee_receipt", "Fee Receipt"),
                            ("student_report", "Student Performance Report"),
                            ("attendance_report", "Attendance Report"),
                            ("transfer_certificate", "Transfer Certificate"),
                            ("bonafide", "Bonafide Certificate"),
                            ("conduct_certificate", "Conduct Certificate"),
                            ("custom", "Custom Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("recipient_name", models.CharField(blank=True, max_length=200)),
                (
                    "recipient_entity",
                    models.CharField(
                        blank=True, help_text="e.g. Class, Department", max_length=200
                    ),
                ),
                ("academic_session", models.CharField(blank=True, max_length=50)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("file", models.FileField(upload_to="generated_documents/")),
                ("file_format", models.CharField(default="docx", max_length=10)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to="administration.documenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Document",
                "verbose_name_plural": "Generated Documents",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("document_type",),
                name="unique_active_template_per_type",
            ),
        ),
    ]
