# Generated by Django 6.0.4 on 2026-07-28 16:25

import administration.models.website
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0017_documenttemplate_generateddocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="facilities/")),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Facility Image",
                "verbose_name_plural": "Facility Images",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="Alt text for accessibility", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="caption",
            field=models.CharField(
                blank=True, help_text="Display caption", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="WebsiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("home_hero", "Home Hero"),
                            ("home_collage_1", "Home Collage 1"),
                            ("home_collage_2", "Home Collage 2"),
                            ("home_collage_3", "Home Collage 3"),
                            ("about_hero", "About Hero"),
                            ("about_video_thumbnail", "About Video Thumbnail"),
                            ("contact_hero", "Contact Hero"),
                            ("facilities_hero", "Facilities Hero"),
                        ],
                        help_text="Each slot can have at most one active image.",
                        max_length=50,
                        unique=True,
                        verbose_name="Website Slot",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=administration.models.website.website_image_upload_to
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Image",
                "verbose_name_plural": "Website Images",
            },
        ),
    ]
