# Generated by Django 6.0.4 on 2026-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0019_facilityimage_uploaded_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                ("quote", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leadership",
                "verbose_name_plural": "Leadership",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public Announcement",
                "verbose_name_plural": "Public Announcements",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="approach_description",
            field=models.TextField(
                blank=True, help_text="Educational approach description"
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="approach_title",
            field=models.CharField(
                blank=True, help_text="Educational approach title", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="foundations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {title, description} foundation objects",
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="milestones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {year, title, description} milestone objects",
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="mission",
            field=models.TextField(
                blank=True, help_text="Institution mission statement"
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="mission_description",
            field=models.TextField(
                blank=True, help_text="Expanded mission description"
            ),
        ),
        migrations.AddField(
            model_name="aboutpagecontent",
            name="pillars",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {title, description} pillar objects",
            ),
        ),
        migrations.AddField(
            model_name="admissionpagecontent",
            name="contact_info",
            field=models.TextField(
                blank=True, help_text="Admission office contact information"
            ),
        ),
        migrations.AddField(
            model_name="admissionpagecontent",
            name="documents_required",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of required document descriptions",
            ),
        ),
        migrations.AddField(
            model_name="admissionpagecontent",
            name="eligibility",
            field=models.TextField(
                blank=True, help_text="Admission eligibility criteria"
            ),
        ),
        migrations.AddField(
            model_name="admissionpagecontent",
            name="fee_info",
            field=models.TextField(blank=True, help_text="Admission fee information"),
        ),
        migrations.AddField(
            model_name="admissionpagecontent",
            name="process_steps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {step, title, description} admission process steps",
            ),
        ),
        migrations.AddField(
            model_name="admissionpagecontent",
            name="reservation_info",
            field=models.TextField(
                blank=True, help_text="Reservation/quota information"
            ),
        ),
    ]
