# Generated by Django 6.0.4 on 2026-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0020_faq_leadership_publicannouncement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="new_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
