# Generated by Django 6.0.4 on 2026-06-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="subject",
            name="color",
            field=models.CharField(
                blank=True, default="from-blue-500 to-indigo-500", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studentsubject",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Admin Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("selected", "Selected"),
                    ("request_pending", "Request Pending"),
                    ("not_selected", "Not Selected"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="tier",
            field=models.CharField(
                choices=[
                    ("core", "Core"),
                    ("specialized", "Specialized"),
                    ("enrichment", "Enrichment"),
                ],
                max_length=20,
            ),
        ),
    ]
