# Generated by Django 6.0.4 on 2026-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_studentprofile_blood_group_studentprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("marked", "Marked"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
