# Generated by Django 6.0.4 on 2026-07-06 17:02

import django.db.models.deletion
import student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_assignment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submissions/",
                validators=[
                    student.validators.FileExtensionValidator(
                        [".pdf", ".ppt", ".pptx"]
                    ),
                    student.validators.FileSizeValidator(10485760),
                ],
            ),
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="submissions/",
                        validators=[
                            student.validators.FileExtensionValidator(
                                [".pdf", ".ppt", ".pptx"]
                            ),
                            student.validators.FileSizeValidator(10485760),
                        ],
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=20)),
                ("file_size", models.BigIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="student.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
