# Generated by Django 6.0.4 on 2026-07-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_academicsession_alter_exportlog_export_type_class"),
        ("student", "0004_alter_assignmentsubmission_file_submissionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubject",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_subject_allocations",
                to="administration.academicsession",
            ),
        ),
    ]
