# Generated by Django 6.0.4 on 2026-07-26 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0014_classsubjectconfig_and_more"),
        ("student", "0005_studentsubject_academic_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentsubject",
            unique_together={("student", "subject", "academic_session")},
        ),
        migrations.AddField(
            model_name="subject",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="administration.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="studentsubject",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Admin Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("selected", "Selected"),
                    ("request_pending", "Request Pending"),
                    ("not_selected", "Not Selected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="not_selected",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubjectWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for withdrawal")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_remark", models.TextField(blank=True)),
                (
                    "has_marks",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student has marks in this subject (auto-detected)",
                    ),
                ),
                (
                    "exceptional_override",
                    models.BooleanField(
                        default=False, help_text="Admin override for marks block"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replacement_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requests",
                        to="student.subject",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="student.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Withdrawal Request",
                "ordering": ["-created_at"],
            },
        ),
    ]
