# Generated by Django 6.0.4 on 2026-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_studentsubject_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="github_username",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
