# Generated by Django 6.0.4 on 2026-07-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionMarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_label", models.CharField(max_length=50)),
                ("question_title", models.CharField(blank=True, max_length=200)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "obtained_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "answer_script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_marks",
                        to="teacher.answerscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Marks",
                "verbose_name_plural": "Question Marks",
                "ordering": ["order"],
            },
        ),
    ]
