# Generated by Django 6.0.4 on 2026-07-06 17:55

import student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_questionmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="download_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                upload_to="resources/",
                validators=[
                    student.validators.FileExtensionValidator(
                        [
                            ".pdf",
                            ".doc",
                            ".docx",
                            ".ppt",
                            ".pptx",
                            ".jpg",
                            ".jpeg",
                            ".png",
                            ".mp4",
                            ".zip",
                        ]
                    ),
                    student.validators.FileSizeValidator(104857600),
                ],
            ),
        ),
    ]
