# Generated by Django 6.0.4 on 2026-07-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_studentsubject_academic_session"),
        ("teacher", "0003_add_resource_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "progress_weight",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Weight for progress calculation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="student.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="teacher.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="ClassChapterProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(help_text="e.g. X-A", max_length=20)),
                ("completed_topics", models.PositiveSmallIntegerField(default=0)),
                ("total_topics", models.PositiveSmallIntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_progress",
                        to="teacher.chapter",
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter", "class_name")},
            },
        ),
    ]
