# Generated by Django 6.0.4 on 2026-07-26 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_chapter_topic_classchapterprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("science", "Science"),
                    ("arts", "Arts"),
                    ("commerce", "Commerce"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "Teacher"),
                    ("senior_teacher", "Senior Teacher"),
                    ("vp", "Vice Principal"),
                    ("principal", "Principal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resigned", "Resigned"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TeacherResignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("details", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("effective_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("overridden", "Overridden"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("override_at", models.DateTimeField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True)),
                ("admin_notified", models.BooleanField(default=False)),
                (
                    "override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_resignations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_resignations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resignations",
                        to="teacher.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Resignation",
                "verbose_name_plural": "Teacher Resignations",
                "ordering": ["-requested_at"],
            },
        ),
    ]
