# Generated by Django 6.0.4 on 2026-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teacher",
            "0005_teacherprofile_address_teacherprofile_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("teacher", "day_of_week", "start_time"),
                name="unique_teacher_time_slot",
                violation_error_message="Teacher already has a class at this time slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("class_name", "day_of_week", "start_time"),
                name="unique_class_time_slot",
                violation_error_message="Class already has a lesson at this time slot",
            ),
        ),
    ]
