# Generated by Django 6.0.4 on 2026-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0006_timetableentry_unique_teacher_time_slot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="github_username",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
